[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [[headers]]
  for = "/data/verifications.json"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

